-module(wasm_wast).
-moduledoc """
Specification scripts: the `.wast` format the conformance suite is written in.
You want this only if you are running the suite.

A `.wast` file is a module interleaved with assertions about it. This reads one
into the command list the runner already understands, so the suite can be
replayed from the upstream source rather than from fixtures generated by
another tool.

## The shape is the tool's, deliberately

Commands come out in the same shape `wasm-tools json-from-wast` produces:
binary keys, `assert_return` carrying `action` and `expected`, values as
`#{type, value}` with integers signed and floats as bit patterns. That is not
imitation for its own sake. It means the runner reads both, and the two can be
compared command by command over the whole suite, which is the only way to know
this file agrees with the tool it replaces.

The one difference is where a module comes from. The tool writes a `.wasm` file
and names it; here the module travels with the command as `{form, Sexp}`,
`{quote, Source}` or `{binary, Bytes}`.

## Modules are not parsed here

A script is read whole and its modules parsed one at a time afterwards. Parsing
them while reading would mean a file containing one deliberately malformed
module could not be read at all, and `assert_malformed` is a third of what the
suite asserts.
""".

-export([script/1, commands/1]).

-export_type([command/0, module_source/0]).

-doc "A script command, in the shape the runner consumes.".
-type command() :: #{binary() => term()}.

-doc """
Where a command's module comes from.

`form` is text already read; `quote` is text carried as a string and not yet
read; `binary` is the bytes of a module written out directly.
""".
-type module_source() :: {form, wasm_wat_sexp:sexp()}
                       | {quote, binary()}
                       | {binary, binary()}.

-doc "Read a script, or fail with a structured error.".
-spec script(binary()) -> {ok, [command()]} | {error, wasm_error:error()}.
script(Source) ->
    wasm_error:capture(fun() -> {ok, commands(Source)} end).

-doc "As `script/1`, but raising rather than answering.".
-spec commands(binary()) -> [command()].
commands(Source) ->
    Lines = line_index(Source),
    case wasm_wat_sexp:forms_of(Source) of
        [] -> [];
        Forms ->
            case lists:all(fun is_command/1, Forms) of
                true -> [command(Form, Lines) || Form <- Forms]; %% A file may leave the `(module ...)' out entirely and be
                %% nothing but its fields, in which case the file is the module.
                false -> [whole_file(Forms, Lines)]
            end
    end.

is_command({list, _, [{keyword, _, Kind} | _]}) ->
    lists:member(Kind, [<<"module">>, <<"register">>, <<"invoke">>, <<"get">>,
                        <<"assert_return">>, <<"assert_trap">>,
                        <<"assert_exhaustion">>, <<"assert_malformed">>,
                        <<"assert_invalid">>, <<"assert_unlinkable">>,
                        <<"assert_uninstantiable">>, <<"assert_exception">>]);
is_command(_Form) ->
    false.

whole_file(Forms, Lines) ->
    #{<<"type">> => <<"module">>, <<"line">> => line_of(position(hd(Forms)), Lines),
      <<"module_type">> => <<"binary">>, <<"module">> => {form, module_form(Forms)}}.

%%% -------------------------------------------------------------- commands ---

command({list, _, [{keyword, _, Kind} | Args]} = Form, Lines) ->
    Base = #{<<"type">> => Kind, <<"line">> => line_of(subject(Form), Lines)},
    kind(Kind, Args, Base, Form);
command(Form, _Lines) ->
    fail(unexpected_command, Form).

%% A command is reported at the line of what it is about: a module at its own,
%% an assertion at its module's or action's. The two differ whenever the suite
%% wraps the inner form onto the following line, as it does for nearly every
%% `assert_invalid' and `assert_malformed' it contains.
subject({list, _, [{keyword, _, <<"module">>} | _]} = Form) -> position(Form);
subject({list, _, [_Keyword, First | _]}) -> position(First);
subject(Form) -> position(Form).

%% A parenthesised form is at its keyword rather than at its parenthesis. The
%% two are usually the same character apart and occasionally a line, because a
%% comment may sit between them.
position({list, _, [{keyword, Pos, _} | _]}) -> Pos;
position({list, Pos, _}) -> Pos;
position({_Kind, Pos}) -> Pos;
position({_Kind, Pos, _}) -> Pos.

%% A bare module establishes the instance the assertions that follow run
%% against. `(module definition ...)' and `(module instance ...)' are the
%% component model's, and are carried through under their own names so the
%% runner reports them the way it always has.
kind(<<"module">>, [{keyword, _, <<"definition">>} | Rest], Base, _Form) ->
    {Name, Body} = optional_name(Rest),
    with_name(Base#{<<"type">> => <<"module_definition">>,
                    <<"module_type">> => <<"binary">>,
                    <<"module">> => {form, module_form(Body)}}, Name);
kind(<<"module">>, [{keyword, _, <<"instance">>} | Rest], Base, _Form) ->
    {Instance, Rest1} = optional_name(Rest),
    {Module, _} = optional_name(Rest1),
    Base#{<<"type">> => <<"module_instance">>,
          <<"instance">> => Instance, <<"module">> => Module};
kind(<<"module">>, Args, Base, Form) ->
    {Name, Rest} = optional_name(Args),
    {Type, Source} = module_source(Rest, Form),
    with_name(Base#{<<"module_type">> => Type, <<"module">> => Source}, Name);
kind(<<"register">>, [{string, _, As} | Rest], Base, _Form) ->
    {Name, _} = optional_name(Rest),
    with_name(Base#{<<"as">> => As}, Name);
kind(<<"invoke">>, _Args, Base, Form) ->
    Base#{<<"type">> => <<"action">>, <<"action">> => action(Form)};
kind(<<"get">>, _Args, Base, Form) ->
    Base#{<<"type">> => <<"action">>, <<"action">> => action(Form)};
kind(<<"assert_return">>, [Action | Expected], Base, _Form) ->
    Base#{<<"action">> => action(Action),
          <<"expected">> => [value(E) || E <- Expected]};
kind(<<"assert_exception">>, [Action], Base, _Form) ->
    Base#{<<"action">> => action(Action)};
kind(Kind, [Action, {string, _, Text}], Base, _Form)
  when Kind =:= <<"assert_trap">>; Kind =:= <<"assert_exhaustion">> ->
    %% `assert_trap' also covers a module whose start function traps, which
    %% every other tool spells `assert_uninstantiable'.
    case Action of
        {list, _, [{keyword, _, <<"module">>} | _]} ->
            module_assertion(<<"assert_uninstantiable">>, Action, Text, Base);
        _ ->
            Base#{<<"action">> => action(Action), <<"text">> => Text}
    end;
kind(Kind, [Module, {string, _, Text}], Base, _Form)
  when Kind =:= <<"assert_malformed">>; Kind =:= <<"assert_invalid">>;
       Kind =:= <<"assert_unlinkable">>; Kind =:= <<"assert_uninstantiable">> ->
    module_assertion(Kind, Module, Text, Base);
kind(Kind, _Args, _Base, Form) ->
    fail(unknown_command, {Kind, Form}).

module_assertion(Kind, {list, _, [{keyword, _, <<"module">>} | Args]} = Form,
                 Text, Base) ->
    {Type, Source} = module_source(Args, Form),
    Base#{<<"type">> => Kind, <<"module_type">> => Type,
          <<"module">> => Source, <<"text">> => Text};
module_assertion(_Kind, Form, _Text, _Base) ->
    fail(expected_module, Form).

%% `(module binary "...")' is bytes and `(module quote "...")' is text that has
%% not been read yet. Anything else is a module written out in full, which has
%% been read already and travels as the form it was read into.
module_source([{keyword, _, <<"binary">>} | Strings], _Form) ->
    {<<"binary">>, {binary, strings(Strings)}};
module_source([{keyword, _, <<"quote">>} | Strings], _Form) ->
    {<<"text">>, {quote, strings(Strings)}};
module_source(_Args, Form) ->
    {<<"binary">>, {form, Form}}.

module_form({list, _, _} = Form) -> Form;
module_form(Forms) -> {list, 0, [{keyword, 0, <<"module">>} | Forms]}.

with_name(Command, undefined) -> Command;
with_name(Command, Name) -> Command#{<<"name">> => Name}.

optional_name([{id, _, Name} | Rest]) -> {Name, Rest};
optional_name(Forms) -> {undefined, Forms}.

strings(Forms) -> iolist_to_binary([S || {string, _, S} <- Forms]).

%%% --------------------------------------------------------------- actions ---

action({list, _, [{keyword, _, <<"invoke">>} | Args]}) ->
    {Module, [{string, _, Field} | Values]} = optional_name(Args),
    with_module(#{<<"type">> => <<"invoke">>, <<"field">> => Field,
                  <<"args">> => [value(V) || V <- Values]}, Module);
action({list, _, [{keyword, _, <<"get">>} | Args]}) ->
    {Module, [{string, _, Field}]} = optional_name(Args),
    with_module(#{<<"type">> => <<"get">>, <<"field">> => Field}, Module);
action(Form) ->
    fail(unknown_action, Form).

with_module(Action, undefined) -> Action;
with_module(Action, Module) -> Action#{<<"module">> => Module}.

%%% ---------------------------------------------------------------- values ---

%% A value is written as the instruction that would produce it. Integers come
%% out as signed decimal and floats as their bit pattern, because that is the
%% only notation that can name a NaN payload or tell the two zeroes apart.
value({list, _, [{keyword, _, <<"i32.const">>}, Literal]}) ->
    #{<<"type">> => <<"i32">>, <<"value">> => signed(Literal, i32)};
value({list, _, [{keyword, _, <<"i64.const">>}, Literal]}) ->
    #{<<"type">> => <<"i64">>, <<"value">> => signed(Literal, i64)};
value({list, _, [{keyword, _, <<"f32.const">>}, Literal]}) ->
    #{<<"type">> => <<"f32">>, <<"value">> => float_pattern(Literal, 32)};
value({list, _, [{keyword, _, <<"f64.const">>}, Literal]}) ->
    #{<<"type">> => <<"f64">>, <<"value">> => float_pattern(Literal, 64)};
value({list, _, [{keyword, _, <<"v128.const">>}, {keyword, _, Shape} | Lanes]}) ->
    #{<<"type">> => <<"v128">>, <<"lane_type">> => lane_type(Shape),
      <<"value">> => [lane(Shape, L) || L <- Lanes]};
%% `(either ...)' is how the relaxed instructions name the several answers the
%% specification permits for one input.
value({list, _, [{keyword, _, <<"either">>} | Alternatives]}) ->
    #{<<"type">> => <<"either">>,
      <<"values">> => [value(A) || A <- Alternatives]};
%% The bottom of each hierarchy holds exactly one value, so naming it would say
%% nothing the type has not already said.
value({list, _, [{keyword, _, <<"ref.null">>}, {keyword, _, Heap}]}) ->
    case null_type(Heap) of
        Bottom when Bottom =:= <<"nullref">>; Bottom =:= <<"nullfuncref">>;
                    Bottom =:= <<"nullexternref">>; Bottom =:= <<"nullexnref">> ->
            #{<<"type">> => Bottom};
        Type ->
            #{<<"type">> => Type, <<"value">> => <<"null">>}
    end;
value({list, _, [{keyword, _, <<"ref.extern">>}, Literal]}) ->
    #{<<"type">> => <<"externref">>, <<"value">> => signed(Literal, u32)};
value({list, _, [{keyword, _, <<"ref.host">>}, Literal]}) ->
    #{<<"type">> => <<"anyref">>, <<"value">> => signed(Literal, u32)};
value({list, _, [{keyword, _, <<"ref.i31">>}, Literal]}) ->
    #{<<"type">> => <<"i31ref">>, <<"value">> => signed(Literal, u32)};
%% A reference named without a value asserts only what kind came back.
value({list, _, [{keyword, _, Name}]}) ->
    case reference_kind(Name) of
        false -> fail(unknown_value, Name);
        Type -> #{<<"type">> => Type}
    end;
value(Form) ->
    fail(unknown_value, Form).

reference_kind(<<"ref.func">>) -> <<"funcref">>;
reference_kind(<<"ref.extern">>) -> <<"externref">>;
reference_kind(<<"ref.any">>) -> <<"anyref">>;
reference_kind(<<"ref.eq">>) -> <<"eqref">>;
reference_kind(<<"ref.i31">>) -> <<"i31ref">>;
reference_kind(<<"ref.struct">>) -> <<"structref">>;
reference_kind(<<"ref.array">>) -> <<"arrayref">>;
reference_kind(<<"ref.exn">>) -> <<"exnref">>;
reference_kind(<<"ref.null">>) -> <<"refnull">>;
reference_kind(_Name) -> false.

null_type(<<"func">>) -> <<"funcref">>;
null_type(<<"extern">>) -> <<"externref">>;
null_type(<<"any">>) -> <<"anyref">>;
null_type(<<"eq">>) -> <<"eqref">>;
null_type(<<"i31">>) -> <<"i31ref">>;
null_type(<<"struct">>) -> <<"structref">>;
null_type(<<"array">>) -> <<"arrayref">>;
null_type(<<"exn">>) -> <<"exnref">>;
null_type(<<"none">>) -> <<"nullref">>;
null_type(<<"nofunc">>) -> <<"nullfuncref">>;
null_type(<<"noextern">>) -> <<"nullexternref">>;
null_type(<<"noexn">>) -> <<"nullexnref">>;
null_type(Heap) -> fail(unknown_heaptype, Heap).

lane_type(<<"i8x16">>) -> <<"i8">>;
lane_type(<<"i16x8">>) -> <<"i16">>;
lane_type(<<"i32x4">>) -> <<"i32">>;
lane_type(<<"i64x2">>) -> <<"i64">>;
lane_type(<<"f32x4">>) -> <<"f32">>;
lane_type(<<"f64x2">>) -> <<"f64">>;
lane_type(Shape) -> fail(unknown_vector_shape, Shape).

lane(<<"f32x4">>, Literal) -> float_pattern(Literal, 32);
lane(<<"f64x2">>, Literal) -> float_pattern(Literal, 64);
lane(Shape, Literal) -> signed(Literal, lane_kind(Shape)).

lane_kind(<<"i8x16">>) -> i8;
lane_kind(<<"i16x8">>) -> i16;
lane_kind(<<"i32x4">>) -> i32;
lane_kind(<<"i64x2">>) -> i64.

%% Written as either reading of the same bits and reported as the signed one,
%% which is how the runtime holds an integer.
signed({keyword, _, Literal}, Kind) ->
    case wasm_wat_num:integer(Literal, widest(Kind)) of
        {ok, V} -> integer_to_binary(narrow(V, Kind));
        error -> fail(malformed_integer, Literal)
    end;
signed(Form, _Kind) ->
    fail(unexpected_literal, Form).

widest(i8) -> i32;
widest(i16) -> i32;
widest(i32) -> i32;
widest(u32) -> i32;
widest(i64) -> i64.

narrow(V, i8) -> sign_extend(V band 16#FF, 8);
narrow(V, i16) -> sign_extend(V band 16#FFFF, 16);
%% A host reference is a plain number, not a two's complement pattern.
narrow(V, u32) -> V band 16#FFFFFFFF;
narrow(V, _Kind) -> V.

sign_extend(V, Bits) when V >= (1 bsl (Bits - 1)) -> V - (1 bsl Bits);
sign_extend(V, _Bits) -> V.

%% `nan:canonical' and `nan:arithmetic' name a *set* of values rather than one,
%% so they stay as they are written and the matcher decides what they admit.
float_pattern({keyword, _, <<"nan:canonical">>}, _Width) -> <<"nan:canonical">>;
float_pattern({keyword, _, <<"nan:arithmetic">>}, _Width) -> <<"nan:arithmetic">>;
float_pattern({keyword, _, Literal}, Width) ->
    case wasm_wat_num:float_bits(Literal, Width) of
        {ok, Bits} -> integer_to_binary(Bits);
        error -> fail(malformed_float, Literal)
    end;
float_pattern(Form, _Width) ->
    fail(unexpected_literal, Form).

%%% ----------------------------------------------------------------- lines ---

%% Commands carry the line they start on, because that is how a failure is
%% found in a file of fifty thousand of them. The lexer reports byte offsets,
%% so the newlines are indexed once rather than counted per command.
line_index(Source) ->
    array:from_list([Pos || {Pos, _} <- binary:matches(Source, <<"\n">>)]).

line_of(Offset, Lines) ->
    line_of(Offset, Lines, 0, array:size(Lines)).

line_of(_Offset, _Lines, Low, High) when Low >= High ->
    Low + 1;
line_of(Offset, Lines, Low, High) ->
    Mid = (Low + High) div 2,
    case array:get(Mid, Lines) < Offset of
        true -> line_of(Offset, Lines, Mid + 1, High);
        false -> line_of(Offset, Lines, Low, Mid)
    end.

fail(Kind, Detail) ->
    wasm_error:malformed(Kind, atom_to_binary(Kind),
                         #{detail => iolist_to_binary(io_lib:format("~0P",
                                                                    [Detail, 8]))}).
